sudo: required

services:
  - docker

env:
  - IMAGE=ubuntu:rolling
  - IMAGE=fedora:latest

language: c

script:
  - docker pull $IMAGE
  - cid=`docker run --tty --detach --volume $TRAVIS_BUILD_DIR:/snapd-glib --workdir /snapd-glib $IMAGE bash`
  - if [ $IMAGE = "ubuntu:rolling" ]; then docker exec $cid apt-get update; fi
  - if [ $IMAGE = "ubuntu:rolling" ]; then docker exec $cid apt-get install -y --no-install-recommends gtk-doc-tools intltool libgirepository1.0-dev libglib2.0-dev libjson-glib-dev libpolkit-gobject-1-dev libsoup2.4-dev libtool qtbase5-dev qtdeclarative5-dev valac; fi
  - if [ $IMAGE = "fedora:latest" ]; then docker exec $cid dnf install -y gcc gcc-c++ gobject-introspection-devel glib2-devel gtk-doc intltool json-glib-devel libsoup-devel libtool polkit-devel qt5-qtbase-devel qt5-qtdeclarative-devel redhat-rpm-config vala; fi
  - docker exec $cid ./autogen.sh --disable-silent-rules --enable-gtk-doc
  - docker exec $cid make
  - docker exec $cid make check
